import Providers from './Providers'
import Navbar from './components/navbar/Navbar'


import './globals.css'
import { store } from '@/store/store'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers >
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
